/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sigha.view;

import br.com.sigha.beans.ConfigBeans;
import br.com.sigha.beans.OperadorBeans;
import br.com.sigha.beans.OperadorLogadoBeans;
import br.com.sigha.beans.UnidadeBeans;
import br.com.sigha.beans.UnidadeLogadoBeans;
import br.com.sigha.config.Config;
import br.com.sigha.dao.OperadorDao;
import br.com.sigha.dao.UnidadeDao;
import com.jtattoo.plaf.acryl.AcrylLookAndFeel;
import com.jtattoo.plaf.aero.AeroLookAndFeel;
import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import com.jtattoo.plaf.bernstein.BernsteinLookAndFeel;
import com.jtattoo.plaf.fast.FastLookAndFeel;
import com.jtattoo.plaf.graphite.GraphiteLookAndFeel;
import com.jtattoo.plaf.hifi.HiFiLookAndFeel;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.LookAndFeel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import org.jdom2.Attribute;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.output.XMLOutputter;

/**
 *
 * @author MarcosVinicius
 */
public class ViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form viewLogin
     */
    List<UnidadeBeans> lunb;
    int idtema;
    int idunidade;

    public ViewLogin() {
        initComponents();
        ListaUnidade();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDconfig = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTlocalbanco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        jTsenha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDunidade = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTunidade = new javax.swing.JTable();
        jPMtema = new javax.swing.JPopupMenu();
        jMIAero = new javax.swing.JMenuItem();
        jMIAcryl = new javax.swing.JMenuItem();
        jMIAluminim = new javax.swing.JMenuItem();
        jMIBernstein = new javax.swing.JMenuItem();
        jMIFast = new javax.swing.JMenuItem();
        jMIGraphite = new javax.swing.JMenuItem();
        jMIHifi = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTcancelar = new javax.swing.JToggleButton();
        jBok = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPsenha = new javax.swing.JPasswordField();
        jLunidade = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jDconfig.setTitle("Configuracao");
        jDconfig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDconfig.setMinimumSize(new java.awt.Dimension(458, 300));
        jDconfig.setModal(true);
        jDconfig.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDconfig.setResizable(false);
        jDconfig.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jDconfigComponentHidden(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONFIGURAÇÃO DO BANCO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setText("Local do Banco:");

        jLabel7.setText("Usuario:");

        jLabel8.setText("Senha:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SALVAR32X32.png"))); // NOI18N
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/CANCELAR.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDconfigLayout = new javax.swing.GroupLayout(jDconfig.getContentPane());
        jDconfig.getContentPane().setLayout(jDconfigLayout);
        jDconfigLayout.setHorizontalGroup(
            jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDconfigLayout.createSequentialGroup()
                .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jDconfigLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTlocalbanco, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jTusuario)
                            .addComponent(jTsenha)))
                    .addGroup(jDconfigLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDconfigLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jDconfigLayout.setVerticalGroup(
            jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDconfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTlocalbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jDunidade.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDunidade.setMinimumSize(new java.awt.Dimension(553, 181));
        jDunidade.setModal(true);
        jDunidade.setResizable(false);
        jDunidade.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jDunidadeComponentShown(evt);
            }
        });

        jTunidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "RAZAO", "FANTASIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTunidade.getTableHeader().setResizingAllowed(false);
        jTunidade.getTableHeader().setReorderingAllowed(false);
        jTunidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTunidadeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTunidade);
        if (jTunidade.getColumnModel().getColumnCount() > 0) {
            jTunidade.getColumnModel().getColumn(0).setResizable(false);
            jTunidade.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jDunidadeLayout = new javax.swing.GroupLayout(jDunidade.getContentPane());
        jDunidade.getContentPane().setLayout(jDunidadeLayout);
        jDunidadeLayout.setHorizontalGroup(
            jDunidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDunidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDunidadeLayout.setVerticalGroup(
            jDunidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDunidadeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPMtema.setLabel("TEMA");
        jPMtema.setName("TEMA"); // NOI18N

        jMIAero.setText("Aero");
        jMIAero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAeroActionPerformed(evt);
            }
        });
        jPMtema.add(jMIAero);

        jMIAcryl.setText("Acryl");
        jMIAcryl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAcrylActionPerformed(evt);
            }
        });
        jPMtema.add(jMIAcryl);

        jMIAluminim.setText("Aluminim");
        jMIAluminim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAluminimActionPerformed(evt);
            }
        });
        jPMtema.add(jMIAluminim);

        jMIBernstein.setText("Bernstein");
        jMIBernstein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBernsteinActionPerformed(evt);
            }
        });
        jPMtema.add(jMIBernstein);

        jMIFast.setText("Fast");
        jMIFast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFastActionPerformed(evt);
            }
        });
        jPMtema.add(jMIFast);

        jMIGraphite.setText("Graphite");
        jMIGraphite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGraphiteActionPerformed(evt);
            }
        });
        jPMtema.add(jMIGraphite);

        jMIHifi.setText("Hifi");
        jMIHifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIHifiActionPerformed(evt);
            }
        });
        jPMtema.add(jMIHifi);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LOGIN USUARIO");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LOGIM USUARIO"));
        jPanel1.setComponentPopupMenu(jPMtema);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Login:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Senha:");

        jTnome.setDocument(new br.com.sigha.util.LimitaCaracterUpper(30)
        );
        jTnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTnomeKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/CANCELAR.png"))); // NOI18N
        jTcancelar.setText("CANCELAR");
        jTcancelar.setMaximumSize(new java.awt.Dimension(121, 32));
        jTcancelar.setMinimumSize(new java.awt.Dimension(121, 32));
        jTcancelar.setPreferredSize(new java.awt.Dimension(121, 32));
        jTcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcancelarActionPerformed(evt);
            }
        });

        jBok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/CONFIRMA32X32.png"))); // NOI18N
        jBok.setText("CONFIRMA");
        jBok.setMaximumSize(new java.awt.Dimension(123, 32));
        jBok.setMinimumSize(new java.awt.Dimension(123, 32));
        jBok.setPreferredSize(new java.awt.Dimension(123, 32));
        jBok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jBok, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/LOGIN128X128.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setText("USUARIO DO SISTEMA");

        jPsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPsenhaKeyPressed(evt);
            }
        });

        jLunidade.setForeground(new java.awt.Color(204, 0, 0));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/home.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setMaximumSize(new java.awt.Dimension(32, 32));
        jButton3.setMinimumSize(new java.awt.Dimension(32, 32));
        jButton3.setPreferredSize(new java.awt.Dimension(32, 32));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTnome, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(jPsenha))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(94, 94, 94))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jPsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnomeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeKeyReleased

    private void jTcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jTcancelarActionPerformed

    private void jBokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBokActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTnome.getText())) {
            if (BuscaOperador()) {
                ViewLogin.this.setVisible(false);
                new ViewPrincipal().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Operador Não Encontrado", "Login", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite o Nome do Usuario", "Login", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBokActionPerformed

    private void jPsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPsenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jBok.doClick();
        }
    }//GEN-LAST:event_jPsenhaKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            new Config().createConfig(jTlocalbanco.getText(), jTusuario.getText(), jTsenha.getText(), "0", "0");
            System.exit(0);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Salvar Configuração\n" + ex);
        }
//        if (criarConfig()) {
//            //JOptionPane.showMessageDialog(null, "Configuração Salva");
//            System.exit(0);
//        } else {
//            JOptionPane.showMessageDialog(null, "Erro ao Salvar Configuração");
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDconfigComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDconfigComponentHidden
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jDconfigComponentHidden

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jDunidade.setLocationRelativeTo(null);
        jDunidade.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jDunidadeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDunidadeComponentShown
        try {
            // TODO add your handling code here:
            lunb = new UnidadeDao().consultarUnidade();
            DefaultTableModel tabelaunidade = (DefaultTableModel) jTunidade.getModel();
            tabelaunidade.setNumRows(0);
            for (int i = 0; i < lunb.size(); i++) {
                tabelaunidade.addRow(new Object[]{lunb.get(i).getRazao(), lunb.get(i).getFantasia()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Buscar Operador", "Login", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jDunidadeComponentShown

    private void jTunidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTunidadeMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < lunb.size(); i++) {
            if (jTunidade.getSelectedRow() == i) {
                idunidade = lunb.get(i).getId();
                try {
                    Properties prop = new Config().getProp();
                    prop.setProperty("empresa", String.valueOf(idunidade));
                    prop.store(new FileOutputStream("./config/config.properties"), null);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao Selecionar Unidade" + ex);
                }
                jDunidade.setVisible(false);
                ListaUnidade();
            }
        }

    }//GEN-LAST:event_jTunidadeMouseClicked

    private void jMIAeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAeroActionPerformed
        // TODO add your handling code here:
        selecionaTema(1);
    }//GEN-LAST:event_jMIAeroActionPerformed

    private void jMIAcrylActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAcrylActionPerformed
        // TODO add your handling code here:
        selecionaTema(2);
    }//GEN-LAST:event_jMIAcrylActionPerformed

    private void jMIAluminimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAluminimActionPerformed
        // TODO add your handling code here:
        selecionaTema(3);
    }//GEN-LAST:event_jMIAluminimActionPerformed

    private void jMIBernsteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBernsteinActionPerformed
        // TODO add your handling code here:
        selecionaTema(4);
    }//GEN-LAST:event_jMIBernsteinActionPerformed

    private void jMIFastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFastActionPerformed
        // TODO add your handling code here:
        selecionaTema(5);
    }//GEN-LAST:event_jMIFastActionPerformed

    private void jMIGraphiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGraphiteActionPerformed
        // TODO add your handling code here:
        selecionaTema(6);
    }//GEN-LAST:event_jMIGraphiteActionPerformed

    private void jMIHifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIHifiActionPerformed
        // TODO add your handling code here:
        selecionaTema(7);
    }//GEN-LAST:event_jMIHifiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            //UIManager.setLookAndFeel(new com.jtattoo.plaf.aluminium.AluminiumLookAndFeel());
            ConfigBeans cf = new Config().getConfig();
            int idtema = cf.getTema();
            UIManager.setLookAndFeel(new ViewLogin().getTema(idtema));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Aplicar Tema" + ex, "Erro Tema", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Ler Arquivo Config " + ex, "Erro Tema", JOptionPane.ERROR_MESSAGE);
        }

//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBok;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDconfig;
    private javax.swing.JDialog jDunidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLunidade;
    private javax.swing.JMenuItem jMIAcryl;
    private javax.swing.JMenuItem jMIAero;
    private javax.swing.JMenuItem jMIAluminim;
    private javax.swing.JMenuItem jMIBernstein;
    private javax.swing.JMenuItem jMIFast;
    private javax.swing.JMenuItem jMIGraphite;
    private javax.swing.JMenuItem jMIHifi;
    private javax.swing.JPopupMenu jPMtema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPsenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jTcancelar;
    private javax.swing.JTextField jTlocalbanco;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTsenha;
    private javax.swing.JTable jTunidade;
    private javax.swing.JTextField jTusuario;
    // End of variables declaration//GEN-END:variables
    //BUSC OPERADOR
    private Boolean BuscaOperador() {
        try {
            OperadorDao opd = new OperadorDao();
            List<OperadorBeans> opb = opd.BuscaOperadores(new UnidadeLogadoBeans().getId());
            for (int i = 0; i < opb.size(); i++) {
                if (jTnome.getText().equals(opb.get(i).getUsuario()) && jPsenha.getText().equals(opb.get(i).getSenha())) {
                    //SE TIVER O USUARIO ELE GRAVA OS DADOS ESTATICAMENTE EM VARIAVEIS
                    OperadorLogadoBeans opl = new OperadorLogadoBeans();
                    opl.setLogadonome(opb.get(i).getNome());
                    opl.setLogadosenhaadm(opb.get(i).getSenhaadm());
                    opl.setLogadotipo(opb.get(i).getTipo());
                    return true;
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Buscar Operador", "Login", JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    private void ListaUnidade() {
        try {
            ConfigBeans cf = new Config().getConfig();
            this.idunidade = cf.getEmpresa();
            UnidadeBeans unb = new UnidadeDao().consultarUnidade(idunidade);
            UnidadeLogadoBeans ulb = new UnidadeLogadoBeans();
            ulb.setBairro(unb.getBairro());
            ulb.setCep(unb.getCep());
            ulb.setCidade(unb.getCidade());
            ulb.setCnpj(unb.getCnpj());
            ulb.setComplemento(unb.getComplemento());
            ulb.setEndereco(unb.getEndereco());
            ulb.setFantasia(unb.getFantasia());
            ulb.setId(unb.getId());
            ulb.setLogo(unb.getLogo());
            ulb.setNumero(unb.getNumero());
            ulb.setRazao(unb.getRazao());
            ulb.setTelefone(unb.getTelefone());
            jLunidade.setText(ulb.getRazao());

        } catch (SQLException | IOException ex) {
            try {
                ConfigBeans cf = new Config().getConfig();
                jTlocalbanco.setText(cf.getLocal());
                jTusuario.setText(cf.getUsuario());
                jTsenha.setText(cf.getSenha());
                JOptionPane.showMessageDialog(null, "Erro ao Conectar ao Banco\n" + ex, "Login", JOptionPane.ERROR_MESSAGE);
                jDconfig.setLocationRelativeTo(null);
                jDconfig.setVisible(true);
            } catch (IOException ex1) {
                JOptionPane.showMessageDialog(null, "Erro ao Ler Arquivo\n" + ex, "Login", JOptionPane.ERROR_MESSAGE);
            }

        }
    }
//salv as coniguracoes do banco ouedita as novas

//    private boolean criarConfig() {
//        try {
//            File file = new File("./config");
//            file.mkdir();
//            file=new File("./config/config.properties");            
//            file.createNewFile();
//            FileInputStream finput=new FileInputStream("./config/config.properties");
//            Properties prop=new Properties();
//            prop.load(finput);
//            prop.put("senha", jTsenha.getText());
//            prop.put("bancolocal", jTlocalbanco.getText());
//            prop.put("usuario", jTsenha.getText());
//            prop.put("tema", "0");
//            prop.put("empresa", "0");            
//            prop.store(new FileOutputStream("./config/config.properties"), null);
//            return true;
//        } catch (IOException ex) {
//            Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
//            return false;
//        }
//        
//    }
    public LookAndFeel getTema(int idtema) {
        Properties props = new Properties();
        props.put("logoString", "Sigha");
        LookAndFeel tema = new com.jtattoo.plaf.aluminium.AluminiumLookAndFeel();
        switch (idtema) {
            case 1:
                AeroLookAndFeel.setCurrentTheme(props);
                tema = new com.jtattoo.plaf.aero.AeroLookAndFeel();
                break;
            case 2:
                AcrylLookAndFeel.setCurrentTheme(props);
                tema = new com.jtattoo.plaf.acryl.AcrylLookAndFeel();
                break;
            case 3:
                AluminiumLookAndFeel.setCurrentTheme(props);
                tema = new com.jtattoo.plaf.aluminium.AluminiumLookAndFeel();
                break;
            case 4:
                BernsteinLookAndFeel.setCurrentTheme(props);
                tema = new com.jtattoo.plaf.bernstein.BernsteinLookAndFeel();
                break;
            case 5:
                FastLookAndFeel.setCurrentTheme(props);
                tema = new com.jtattoo.plaf.fast.FastLookAndFeel();
                break;
            case 6:
                GraphiteLookAndFeel.setCurrentTheme(props);
                tema = new com.jtattoo.plaf.graphite.GraphiteLookAndFeel();
                break;
            case 7:
                HiFiLookAndFeel.setCurrentTheme(props);
                tema = new com.jtattoo.plaf.hifi.HiFiLookAndFeel();
                break;

        }
        return tema;
    }
//troca o tema selecionado

    private void selecionaTema(int idtema) {
        try {
            Properties prop = new Config().getProp();
            prop.setProperty("tema", String.valueOf(idtema));
            prop.store(new FileOutputStream("./config/config.properties"), null);
            this.idtema = idtema;
            //seta o tema
            UIManager.setLookAndFeel(new ViewLogin().getTema(this.idtema));
            //atualiza em temo de execulsão
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Trocar Tema" + ex);
        }
    }
}
