/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.sigha.view;

import br.com.sigha.Beans.CursoBeans;
import br.com.sigha.Beans.MateriaBeans;
import br.com.sigha.Beans.UnidadeLogadoBeans;
import br.com.sigha.Dao.CursoDao;
import br.com.sigha.Dao.MateriaDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MarcosVinicius
 */
public class ViewMaterias extends javax.swing.JPanel {

    /**
     * Creates new form ViewMaterias
     */
    List<MateriaBeans> listamateria;
    private List<CursoBeans> listacurso;

    public ViewMaterias() {
        initComponents();
        ListaCursos();
        ListaMaterias();
        OcultaCampos();
        ChangeListener change1=new ChangeListener() {

                    @Override
                    public void stateChanged(ChangeEvent e) {
                        if((int) jSqtdedia.getValue()>(int) jSqtdesemana.getValue()){
                            jSqtdedia.setValue((int) jSqtdedia.getValue()-1);
                        }
                    }
                };
        ChangeListener change2=new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                if((int) jSqtdedia.getValue()>(int) jSqtdesemana.getValue()){
                            jSqtdesemana.setValue((int) jSqtdedia.getValue());
                        }
            }
        };
                jSqtdedia.addChangeListener(change1);
                jSqtdesemana.addChangeListener(change2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jFhoraanual = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jFhoraaula = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSqtdesemana = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSqtdedia = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jCsequencial = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTmaterias = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jBnovo = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBeditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCcurso = new javax.swing.JComboBox();
        jTnome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCsegunda = new javax.swing.JCheckBox();
        jCterca = new javax.swing.JCheckBox();
        jCquarta = new javax.swing.JCheckBox();
        jCquinta = new javax.swing.JCheckBox();
        jCsexta = new javax.swing.JCheckBox();
        jCsabado = new javax.swing.JCheckBox();
        jCdomingo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTidmateria = new javax.swing.JTextField();
        jRativo = new javax.swing.JRadioButton();
        jCperiodo = new javax.swing.JComboBox();
        jTsigla = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("CARGA HORARIA"));
        jPanel7.setForeground(new java.awt.Color(204, 0, 0));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel18.setText("Carga Horaria Anual");

        try {
            jFhoraanual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFhoraanual.setText("000:00");
        jFhoraanual.setToolTipText("Carga Horária Anual da Disciplina");
        jFhoraanual.setEnabled(false);

        jLabel19.setText("hs");

        jLabel22.setText("Duração Cada Aula");

        try {
            jFhoraaula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFhoraaula.setText("00:00");
        jFhoraaula.setToolTipText("Carga Horária de Cada Aula no Dia");
        jFhoraaula.setEnabled(false);

        jLabel23.setText("hs");

        jLabel16.setText("Quant.Aulas Semanais");

        jSqtdesemana.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSqtdesemana.setToolTipText("Quantidade de Aula na Semana");
        jSqtdesemana.setEnabled(false);
        jSqtdesemana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSqtdesemanaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSqtdesemanaMouseReleased(evt);
            }
        });

        jLabel17.setText("Aulas");

        jLabel20.setText("Quant.Aula Dia");

        jSqtdedia.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSqtdedia.setToolTipText("Quantidade de Aula no dia");
        jSqtdedia.setEnabled(false);

        jLabel21.setText("Aulas");

        jCsequencial.setSelected(true);
        jCsequencial.setText("Sim");
        jCsequencial.setToolTipText("Sé as Aulas no Dia for Seguidamente");
        jCsequencial.setEnabled(false);

        jLabel6.setText("Aulas Sequencial");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jFhoraanual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jFhoraaula, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSqtdesemana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSqtdedia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21))
                    .addComponent(jLabel20))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jCsequencial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFhoraanual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jFhoraaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20)
                    .addComponent(jLabel6))
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSqtdesemana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jSqtdedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jCsequencial)))
        );

        jTmaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DISCIPLINA", "PERIODO", "CURSO", "CARGA H.ANUAL", "QTDE.SEMANAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTmaterias.getTableHeader().setResizingAllowed(false);
        jTmaterias.getTableHeader().setReorderingAllowed(false);
        jTmaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTmateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTmaterias);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/NOVO32X32.png"))); // NOI18N
        jBnovo.setText("NOVO");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SALVAR32X32.png"))); // NOI18N
        jBsalvar.setText("SALVAR");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/EXCLUIR32X32.png"))); // NOI18N
        jBexcluir.setText("EXCLUIR");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/CANCELAR.png"))); // NOI18N
        jBcancelar.setText("CANCELAR");
        jBcancelar.setEnabled(false);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/EDITAR32X32.png"))); // NOI18N
        jBeditar.setText("EDITAR");
        jBeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setText("Periodo");

        jCcurso.setMaximumRowCount(20);
        jCcurso.setToolTipText("Curso que ela Pertence");
        jCcurso.setEnabled(false);

        jTnome.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(50)
        );
        jTnome.setToolTipText("Nome da Disciplina");
        jTnome.setEnabled(false);
        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });
        jTnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTnomeKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DIAS PROVAVEIS DE AULA"));
        jPanel1.setToolTipText("Dias Que Podera Ter Aula");
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jCsegunda.setSelected(true);
        jCsegunda.setText("Segunda-feira");
        jCsegunda.setEnabled(false);

        jCterca.setSelected(true);
        jCterca.setText("Terça-feira");
        jCterca.setEnabled(false);

        jCquarta.setSelected(true);
        jCquarta.setText("Quarta-feira");
        jCquarta.setEnabled(false);

        jCquinta.setSelected(true);
        jCquinta.setText("Quinta-feira");
        jCquinta.setEnabled(false);

        jCsexta.setSelected(true);
        jCsexta.setText("Sexta-feira");
        jCsexta.setEnabled(false);
        jCsexta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCsextaActionPerformed(evt);
            }
        });

        jCsabado.setSelected(true);
        jCsabado.setText("Sabado");
        jCsabado.setEnabled(false);

        jCdomingo.setText("Domingo");
        jCdomingo.setEnabled(false);
        jCdomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCdomingoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCsegunda)
                .addGap(15, 15, 15)
                .addComponent(jCterca)
                .addGap(10, 10, 10)
                .addComponent(jCquarta)
                .addGap(10, 10, 10)
                .addComponent(jCquinta)
                .addGap(2, 2, 2)
                .addComponent(jCsexta)
                .addGap(2, 2, 2)
                .addComponent(jCsabado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCdomingo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCsegunda)
                    .addComponent(jCterca)
                    .addComponent(jCquarta)
                    .addComponent(jCquinta)
                    .addComponent(jCsexta)
                    .addComponent(jCsabado)
                    .addComponent(jCdomingo))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Nome");

        jLabel3.setText("Ano/Periodo");

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Curso");

        jTidmateria.setEnabled(false);

        jRativo.setSelected(true);
        jRativo.setText("Ativo");
        jRativo.setEnabled(false);

        jCperiodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));
        jCperiodo.setToolTipText("Perio/Ano da Disciplina");
        jCperiodo.setEnabled(false);

        jTsigla.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(5)
        );
        jTsigla.setToolTipText("Sigla para Disciplina");
        jTsigla.setEnabled(false);

        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setText("Sigla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTidmateria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jCcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(166, 166, 166)
                                        .addComponent(jRativo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTsigla, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTidmateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTsigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTmateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTmateriasMouseClicked
        // TODO add your handling code here:
        ClickMaterias();
    }//GEN-LAST:event_jTmateriasMouseClicked

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        LimpaTela();
        AtivaTela();
        AtivaSalvarCancelar();
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        if (ValidaDados()) {
            if ("".equals(jTidmateria.getText())) {
                CadastraMateria();
                LimpaTela();
                DesativaTela();
                AtivaNovoExcluirEditar();
                ListaMaterias();
                
            } else {
                AlteraMateria();
                LimpaTela();
                DesativaTela();
                AtivaNovoExcluirEditar();
                ListaMaterias();
            }
        }else {
            JOptionPane.showMessageDialog(null, "A Campos Obrigatorio", "Cadastro Materia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTidmateria.getText())) {
            ExcluiMateria();
            LimpaTela();
            ListaMaterias();
            JOptionPane.showMessageDialog(null, "Registro Excluido", "Cadastro Materia", WIDTH);
        } else {
            JOptionPane.showMessageDialog(null, "Não a Registro Para Excluir", "Cadastro Materia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        LimpaTela();
        AtivaNovoExcluirEditar();
        DesativaTela();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditarActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTidmateria.getText())) {
            AtivaTela();
            AtivaSalvarCancelar();
        } else {
            JOptionPane.showMessageDialog(null, "Não a Registro Selecionado Para Alterar", "Cadastro Materia", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBeditarActionPerformed

    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeActionPerformed

    private void jCsextaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCsextaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCsextaActionPerformed

    private void jCdomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCdomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCdomingoActionPerformed

    private void jTnomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnomeKeyReleased
        // TODO add your handling code here:
        jTnome.setText(jTnome.getText().toUpperCase());
    }//GEN-LAST:event_jTnomeKeyReleased

    private void jSqtdesemanaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSqtdesemanaMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSqtdesemanaMouseReleased

    private void jSqtdesemanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSqtdesemanaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jSqtdesemanaMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       avisoCadastro(); 
    }//GEN-LAST:event_formMouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        avisoCadastro();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        avisoCadastro();
    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBeditar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JComboBox jCcurso;
    private javax.swing.JCheckBox jCdomingo;
    private javax.swing.JComboBox jCperiodo;
    private javax.swing.JCheckBox jCquarta;
    private javax.swing.JCheckBox jCquinta;
    private javax.swing.JCheckBox jCsabado;
    private javax.swing.JCheckBox jCsegunda;
    private javax.swing.JCheckBox jCsequencial;
    private javax.swing.JCheckBox jCsexta;
    private javax.swing.JCheckBox jCterca;
    private javax.swing.JFormattedTextField jFhoraanual;
    private javax.swing.JFormattedTextField jFhoraaula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRativo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSqtdedia;
    private javax.swing.JSpinner jSqtdesemana;
    private javax.swing.JTextField jTidmateria;
    private javax.swing.JTable jTmaterias;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTsigla;
    // End of variables declaration//GEN-END:variables
//lista cursos cadastrados no combobox
    private void ListaCursos() {
        try {
            CursoDao cd = new CursoDao();
            listacurso = cd.BuscaCurso(new UnidadeLogadoBeans().getId());
            jCcurso.removeAllItems();
            for (int i = 0; i < listacurso.size(); i++) {
                jCcurso.addItem(listacurso.get(i).getNome());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro \n" + ex, "Cadastra Materias", JOptionPane.ERROR_MESSAGE);
        }
    }

    //ativa botoes
    private void AtivaNovoExcluirEditar() {
        jBnovo.setEnabled(true);
        jBexcluir.setEnabled(true);
        jBeditar.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBcancelar.setEnabled(false);
        jTmaterias.setEnabled(true);
        

    }

    private void AtivaSalvarCancelar() {
        jBnovo.setEnabled(false);
        jBexcluir.setEnabled(false);
        jBeditar.setEnabled(false);
        jBsalvar.setEnabled(true);
        jBcancelar.setEnabled(true);
        jTmaterias.setEnabled(false);
        jTmaterias.clearSelection();
    }

    private void AtivaTela() {
        jTnome.setEnabled(true);
        jCperiodo.setEnabled(true);
        jCcurso.setEnabled(true);
        jFhoraanual.setEnabled(true);
        jFhoraaula.setEnabled(true);
        jSqtdesemana.setEnabled(true);
        jSqtdedia.setEnabled(true);
        jRativo.setEnabled(true);
        jCsegunda.setEnabled(true);
        jCterca.setEnabled(true);
        jCquarta.setEnabled(true);
        jCquinta.setEnabled(true);
        jCsexta.setEnabled(true);
        jCsabado.setEnabled(true);
        jCdomingo.setEnabled(true);
        jTsigla.setEnabled(true);
        jCsequencial.setEnabled(true);
        
    }

    private void DesativaTela() {
        jTnome.setEnabled(false);
        jCperiodo.setEnabled(false);
        jCcurso.setEnabled(false);
        jFhoraanual.setEnabled(false);
        jFhoraaula.setEnabled(false);
        jSqtdesemana.setEnabled(false);
        jSqtdedia.setEnabled(false);
        jRativo.setEnabled(false);
        jCsegunda.setEnabled(false);
        jCterca.setEnabled(false);
        jCquarta.setEnabled(false);
        jCquinta.setEnabled(false);
        jCsexta.setEnabled(false);
        jCsabado.setEnabled(false);
        jCdomingo.setEnabled(false);
        jTsigla.setEnabled(false);
        jCsequencial.setEnabled(false);
    }

    private void LimpaTela() {
        jTnome.setText("");
        jTidmateria.setText("");
        jCperiodo.setSelectedIndex(0);
        jCcurso.setSelectedIndex(0);
        jFhoraanual.setText("000:00");
        jFhoraaula.setText("00:00");
        jSqtdesemana.setValue(1);
        jSqtdedia.setValue(1);
        jRativo.setSelected(true);
        jCsegunda.setSelected(true);
        jCterca.setSelected(true);
        jCquarta.setSelected(true);
        jCquinta.setSelected(true);
        jCsexta.setSelected(true);
        jCsabado.setSelected(true);
        jCdomingo.setSelected(false);
        jTsigla.setText("");
        jCsequencial.setSelected(true);
    }

    private void CadastraMateria() {
      
        MateriaBeans mb = new MateriaBeans();
        mb.setAtivo(String.valueOf(jRativo.isSelected()));
        mb.setChanual(jFhoraanual.getText());
        mb.setChaula(jFhoraaula.getText());
        mb.setDomingo(String.valueOf(jCdomingo.isSelected()));
        mb.setIdcurso(listacurso.get(jCcurso.getSelectedIndex()).getId());
        mb.setNome(jTnome.getText());
        mb.setPeriodo(Integer.valueOf(jCperiodo.getSelectedItem().toString()));
        mb.setQtdeauladia(String.valueOf(jSqtdedia.getValue()));
        mb.setQtdeaulasem(String.valueOf(jSqtdesemana.getValue()));
        mb.setQuarta(String.valueOf(jCquarta.isSelected()));
        mb.setQuinta(String.valueOf(jCquinta.isSelected()));
        mb.setSabado(String.valueOf(jCsabado.isSelected()));
        mb.setSegunda(String.valueOf(jCsegunda.isSelected()));
        mb.setSexta(String.valueOf(jCsexta.isSelected()));
        mb.setTerca(String.valueOf(jCterca.isSelected()));
        mb.setSigla(jTsigla.getText());
        mb.setSequencial(String.valueOf(jCsequencial.isSelected()));
        try {
            MateriaDao md = new MateriaDao();
            md.CadastraMateria(mb);
            JOptionPane.showMessageDialog(null, "Materia Cadastrada", "Cadastro de Materias", WIDTH);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro \n" + ex, "Cadastro de Materias", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void ListaMaterias() {
        try {
            listamateria = new MateriaDao().BuscaMateria(new UnidadeLogadoBeans().getId());
            DefaultTableModel tabelamateria = (DefaultTableModel) jTmaterias.getModel();
            tabelamateria.setNumRows(0);
            for (int i = 0; i < listamateria.size(); i++) {
                tabelamateria.addRow(new Object[]{listamateria.get(i).getNome(), listamateria.get(i).getPeriodo(),
                    listamateria.get(i).getNomecurso(), listamateria.get(i).getChanual(), listamateria.get(i).getQtdeaulasem()});
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro \n" + ex, null, WIDTH);
        }

    }

    private void ClickMaterias() {
        for (int i = 0; i < listamateria.size(); i++) {
            if (i == jTmaterias.getSelectedRow()) {
                jTidmateria.setText(String.valueOf(listamateria.get(i).getId()));
                jTnome.setText(listamateria.get(i).getNome());
                jCperiodo.setSelectedItem(String.valueOf(listamateria.get(i).getPeriodo()));
                jCcurso.setSelectedItem(listamateria.get(i).getNomecurso());
                jRativo.setSelected(Boolean.valueOf(listamateria.get(i).getAtivo()));
                jFhoraanual.setText(listamateria.get(i).getChanual());
                jFhoraaula.setText(listamateria.get(i).getChaula());
                jSqtdesemana.setValue(Integer.valueOf(listamateria.get(i).getQtdeaulasem()));
                jSqtdedia.setValue(Integer.valueOf(listamateria.get(i).getQtdeauladia()));
                jCsegunda.setSelected(Boolean.valueOf(listamateria.get(i).getSegunda()));
                jCterca.setSelected(Boolean.valueOf(listamateria.get(i).getTerca()));
                jCquarta.setSelected(Boolean.valueOf(listamateria.get(i).getQuarta()));
                jCquinta.setSelected(Boolean.valueOf(listamateria.get(i).getQuinta()));
                jCsexta.setSelected(Boolean.valueOf(listamateria.get(i).getSexta()));
                jCsabado.setSelected(Boolean.valueOf(listamateria.get(i).getSabado()));
                jCdomingo.setSelected(Boolean.valueOf(listamateria.get(i).getDomingo()));
                jTsigla.setText(listamateria.get(i).getSigla());
                jCsequencial.setSelected(Boolean.valueOf(listamateria.get(i).getSequencial()));

            }
        }
    }

    private void AlteraMateria() {
        MateriaBeans mb = new MateriaBeans();
        mb.setAtivo(String.valueOf(jRativo.isSelected()));
        mb.setChanual(jFhoraanual.getText());
        mb.setChaula(jFhoraaula.getText());
        mb.setDomingo(String.valueOf(jCdomingo.isSelected()));
        mb.setIdcurso(listacurso.get(jCcurso.getSelectedIndex()).getId());
        mb.setNome(jTnome.getText());
        mb.setPeriodo(Integer.valueOf(jCperiodo.getSelectedItem().toString()));
        mb.setQtdeauladia(String.valueOf(jSqtdedia.getValue()));
        mb.setQtdeaulasem(String.valueOf(jSqtdesemana.getValue()));
        mb.setQuarta(String.valueOf(jCquarta.isSelected()));
        mb.setQuinta(String.valueOf(jCquinta.isSelected()));
        mb.setSabado(String.valueOf(jCsabado.isSelected()));
        mb.setSegunda(String.valueOf(jCsegunda.isSelected()));
        mb.setSexta(String.valueOf(jCsexta.isSelected()));
        mb.setTerca(String.valueOf(jCterca.isSelected()));
        mb.setId(Integer.valueOf(jTidmateria.getText()));
        mb.setSigla(jTsigla.getText());
        mb.setSequencial(String.valueOf(jCsequencial.isSelected()));
        try {
            MateriaDao md = new MateriaDao();
            md.AlteraMateria(mb);
            JOptionPane.showMessageDialog(null, "Materia Alterada", "Cadastro de Materias", WIDTH);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro \n" + ex, "Cadastro de Materias", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ExcluiMateria() {
        try {
            MateriaDao md = new MateriaDao();
            md.ExcluirMateria(Integer.valueOf(jTidmateria.getText()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro \n" + ex, "Cadastro de Materias", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void OcultaCampos() {
        jTidmateria.setVisible(false);
    }

    private boolean ValidaDados() {
        Boolean ver=false;
        if(!jTnome.getText().equals("") && !jTsigla.getText().equals("")){
            ver=true;
        }
        return ver;
    }
    private void avisoCadastro(){       
        if(jBnovo.isEnabled()&& "".equals(jTnome.getText())){
              JOptionPane.showMessageDialog(null, "Click em Novo Para Cadastrar", "Cadatro", JOptionPane.WARNING_MESSAGE);
        }
    }
}
