/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.sigha.view;
import br.com.sigha.Beans.UnidadeBeans;
import br.com.sigha.Dao.UnidadeDao;
import java.io.File;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MarcosVinicius
 */
public class ViewPCadUnidade extends javax.swing.JPanel {

    /**
     * Creates new form ViewPCadUnidade
     */
    List<UnidadeBeans> listunidade;
    public ViewPCadUnidade() {
        initComponents();
         BuscarUnidade();
        TamanhoTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDArquivo = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jtfCodigo = new javax.swing.JTextField();
        jtfCidade = new javax.swing.JTextField();
        jlRazaoSocial = new javax.swing.JLabel();
        jtfFone = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        jlCidade = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jspCidade = new javax.swing.JScrollPane();
        jtUnidade = new javax.swing.JTable();
        JTrazaosocial = new javax.swing.JTextField();
        jlFantasia = new javax.swing.JLabel();
        jlFone = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jlCEP = new javax.swing.JLabel();
        jFcnpj = new javax.swing.JFormattedTextField();
        jlN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfN = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jlBairro = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jlComplemento = new javax.swing.JLabel();
        jtfFantasia = new javax.swing.JTextField();
        jtfCEP = new javax.swing.JFormattedTextField();

        jDArquivo.setMinimumSize(new java.awt.Dimension(634, 430));
        jDArquivo.setModal(true);
        jDArquivo.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jDArquivo.setResizable(false);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDArquivoLayout = new javax.swing.GroupLayout(jDArquivo.getContentPane());
        jDArquivo.getContentPane().setLayout(jDArquivoLayout);
        jDArquivoLayout.setHorizontalGroup(
            jDArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDArquivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDArquivoLayout.setVerticalGroup(
            jDArquivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDArquivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jtfCodigo.setEditable(false);
        jtfCodigo.setText("0");
        jtfCodigo.setEnabled(false);
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });

        jtfCidade.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(30));
        jtfCidade.setEnabled(false);

        jlRazaoSocial.setForeground(new java.awt.Color(204, 0, 0));
        jlRazaoSocial.setText("Razão Social");

        jtfFone.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(20));
        jtfFone.setEnabled(false);

        jlCodigo.setText("Código");

        jlCidade.setText("Cidade");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbNovo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/NOVO32X32.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.setPreferredSize(new java.awt.Dimension(57, 25));
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/SALVAR32X32.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.setPreferredSize(new java.awt.Dimension(57, 25));
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/EDITAR32X32.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.setPreferredSize(new java.awt.Dimension(57, 25));
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/EXCLUIR32X32.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setPreferredSize(new java.awt.Dimension(57, 25));
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/CANCELAR.png"))); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.setEnabled(false);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtUnidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Razao Social", "Fantasia", "Endereço", "Bairro", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUnidade.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtUnidade.getTableHeader().setResizingAllowed(false);
        jtUnidade.getTableHeader().setReorderingAllowed(false);
        jtUnidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUnidadeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtUnidadeMouseEntered(evt);
            }
        });
        jspCidade.setViewportView(jtUnidade);

        JTrazaosocial.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(80)
        );
        JTrazaosocial.setEnabled(false);
        JTrazaosocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTrazaosocialKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JTrazaosocialKeyReleased(evt);
            }
        });

        jlFantasia.setForeground(new java.awt.Color(204, 0, 0));
        jlFantasia.setText("Fantasia");

        jlFone.setText("Fone");

        jtfComplemento.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(20));
        jtfComplemento.setEnabled(false);

        jlCEP.setText("CEP");

        try {
            jFcnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFcnpj.setText("00.000.000/0000-00");
        jFcnpj.setEnabled(false);

        jlN.setText("N°");

        jLabel1.setText("Cnpj");

        jtfN.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(20)
        );
        jtfN.setEnabled(false);

        jlEndereco.setText("Endereço");

        jtfEndereco.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(80));
        jtfEndereco.setEnabled(false);

        jlBairro.setText("Bairro");

        jtfBairro.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(30));
        jtfBairro.setEnabled(false);

        jlComplemento.setText("Complemento");

        jtfFantasia.setDocument(new br.com.sigha.Util.LimitaCaracterUpper(80)
        );
        jtfFantasia.setEnabled(false);
        jtfFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFantasiaActionPerformed(evt);
            }
        });

        jtfCEP.setEditable(false);
        try {
            jtfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRazaoSocial)
                            .addComponent(JTrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFantasia)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jspCidade)))
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlComplemento))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlFone))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCidade)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEndereco)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlBairro)
                                            .addComponent(jFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlCEP)
                                    .addComponent(jtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfN, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlN))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCodigo)
                        .addGap(5, 5, 5)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlRazaoSocial)
                        .addGap(5, 5, 5)
                        .addComponent(JTrazaosocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlFantasia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jlBairro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFone)
                    .addComponent(jlCidade)
                    .addComponent(jlComplemento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfComplemento)
                    .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jspCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        if (jtUnidade.getRowCount() == 0) {
            Ativatela();
            AtivaSalvarCancelar();
            LimpaTela();
        } else {
            JOptionPane.showMessageDialog(null, "Não e Possivel Cadastrar Mais de Uma Unidade", "Cadastro Unidade", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        if (!"".equals(JTrazaosocial.getText()) && !"".equals(jtfFantasia.getText())) {
            if (Integer.valueOf(jtfCodigo.getText()) > 0) {
                AlteraUnidade();
                AtivaNovoAlterarExcluir();
                Desativatela();
                BuscarUnidade();
                LimpaTela();
            } else {
                SalvaUnidade();
                AtivaNovoAlterarExcluir();
                Desativatela();
                BuscarUnidade();
                LimpaTela();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Campos Obrigatorios Razao e Fantasia");
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(jtfCodigo.getText()) > 0) {
            Ativatela();
            AtivaSalvarCancelar();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Registro para Alterar");
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(jtfCodigo.getText()) > 0) {
            ExcluirUnidade();
            LimpaTela();
            AtivaNovoAlterarExcluir();
            Desativatela();
        } else {
            JOptionPane.showMessageDialog(null, "Nao a registro Para Excluir");
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        Desativatela();
        AtivaNovoAlterarExcluir();
        LimpaTela();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jtUnidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUnidadeMouseClicked
        // TODO add your handling code here:
        ClickUnidade();
    }//GEN-LAST:event_jtUnidadeMouseClicked

    private void jtUnidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUnidadeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUnidadeMouseEntered

    private void JTrazaosocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTrazaosocialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTrazaosocialKeyPressed

    private void JTrazaosocialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTrazaosocialKeyReleased
        // TODO add your handling code here:
        JTrazaosocial.setText(JTrazaosocial.getText().toUpperCase());
    }//GEN-LAST:event_JTrazaosocialKeyReleased

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
        File caminhologo = jFileChooser1.getSelectedFile();
        String caminho = String.valueOf(caminhologo);
        jDArquivo.setVisible(false);

//        if ("null".equals(caminho)) {
//            LogoEmpresa("");
//        } else {
//            LogoEmpresa(caminho);
//        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jtfFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFantasiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTrazaosocial;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JDialog jDArquivo;
    private javax.swing.JFormattedTextField jFcnpj;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlBairro;
    private javax.swing.JLabel jlCEP;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlComplemento;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlFantasia;
    private javax.swing.JLabel jlFone;
    private javax.swing.JLabel jlN;
    private javax.swing.JLabel jlRazaoSocial;
    private javax.swing.JScrollPane jspCidade;
    private javax.swing.JTable jtUnidade;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JFormattedTextField jtfCEP;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfFantasia;
    private javax.swing.JTextField jtfFone;
    private javax.swing.JTextField jtfN;
    // End of variables declaration//GEN-END:variables
 public void BuscarUnidade() {

        try {
            UnidadeDao unidade = new UnidadeDao();
            listunidade = unidade.consultarUnidade();
            //JOptionPane.showMessageDialog(null, "Foi0");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Listar Unidade" + ex.toString());
        }
        ListaUnidadeTabela(listunidade);
    }

    private void ListaUnidadeTabela(List<UnidadeBeans> listunidade) {
        DefaultTableModel tabelaunidade = (DefaultTableModel) jtUnidade.getModel();
        tabelaunidade.setNumRows(0);
        for (int i = 0; i < listunidade.size(); i++) {
            tabelaunidade.addRow(new Object[]{listunidade.get(i).getId(), listunidade.get(i).getRazao(),
                listunidade.get(i).getFantasia(), listunidade.get(i).getEndereco(), listunidade.get(i).getBairro(), listunidade.get(i).getCidade()});
        }
    }

    private void Ativatela() {
        jtfBairro.setEnabled(true);
        jtfCEP.setEnabled(true);
        jtfCidade.setEnabled(true);
        jtfComplemento.setEnabled(true);
        jtfEndereco.setEnabled(true);
        jtfFantasia.setEnabled(true);
        jtfFone.setEnabled(true);
        jtfN.setEnabled(true);
        JTrazaosocial.setEnabled(true);
        jFcnpj.setEnabled(true);
    }

    private void Desativatela() {
        jtfBairro.setEnabled(false);
        jtfCEP.setEnabled(false);
        jtfCidade.setEnabled(false);
        jtfComplemento.setEnabled(false);
        jtfEndereco.setEnabled(false);
        jtfFantasia.setEnabled(false);
        jtfFone.setEnabled(false);
        jtfN.setEnabled(false);
        JTrazaosocial.setEnabled(false);
        jFcnpj.setEnabled(false);
    }

    private void AtivaSalvarCancelar() {
        jbSalvar.setEnabled(true);
        jbAlterar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbNovo.setEnabled(false);
     //   jBlogo.setEnabled(true);
        jBcancelar.setEnabled(true);
    }

    private void AtivaNovoAlterarExcluir() {
        jbSalvar.setEnabled(false);
        jbAlterar.setEnabled(true);
        jbExcluir.setEnabled(true);
        jbNovo.setEnabled(true);
    //    jBlogo.setEnabled(false);
        jBcancelar.setEnabled(false);
    }

    public void LimpaTela() {
        jtfCodigo.setText("0");
        jtfBairro.setText("");
        jtfCEP.setText("");
        jtfCidade.setText("");
        jtfComplemento.setText("");
        jtfEndereco.setText("");
        jtfFantasia.setText("");
        jtfFone.setText("");
        jtfN.setText("");
        JTrazaosocial.setText("");
      //  LogoEmpresa("");
        jFcnpj.setText("00.000.000/0000-00");
    }

//    private void LogoEmpresa(String id) {
//        if (!"".equals(id)) {
//            jlLogo.setIcon(new javax.swing.ImageIcon(id));
//        } else {
//            jlLogo.setIcon(new javax.swing.ImageIcon(""));
//        }
//    }

    private void ClickUnidade() {
        for (int i = 0; i < listunidade.size(); i++) {
            if (i == jtUnidade.getSelectedRow()) {
                jtfCodigo.setText(String.valueOf(listunidade.get(i).getId()));
                jtfBairro.setText(listunidade.get(i).getBairro());
                jtfCEP.setText(listunidade.get(i).getCep());
                jtfCidade.setText(listunidade.get(i).getCidade());
                jtfComplemento.setText(listunidade.get(i).getComplemento());
                jtfEndereco.setText(listunidade.get(i).getEndereco());
                jtfFantasia.setText(listunidade.get(i).getFantasia());
                jtfFone.setText(listunidade.get(i).getTelefone());
                jtfN.setText(listunidade.get(i).getNumero());
                JTrazaosocial.setText(listunidade.get(i).getRazao());
            //    LogoEmpresa(listunidade.get(i).getLogo());
                jFcnpj.setText(listunidade.get(i).getCnpj());
            }
        }
    }

    private void SalvaUnidade() {
        UnidadeBeans unidadebeans = new UnidadeBeans();

        unidadebeans.setBairro(jtfBairro.getText());
        unidadebeans.setCep(jtfCEP.getText());
        unidadebeans.setCidade(jtfCidade.getText());
        unidadebeans.setComplemento(jtfComplemento.getText());
        unidadebeans.setEndereco(jtfEndereco.getText());
        unidadebeans.setFantasia(jtfFantasia.getText());
        unidadebeans.setTelefone(jtfFone.getText());
        unidadebeans.setNumero(jtfN.getText());
        unidadebeans.setRazao(JTrazaosocial.getText());
        unidadebeans.setCnpj(jFcnpj.getText());
        unidadebeans.setLogo("");

        try {
            UnidadeDao unidadedao = new UnidadeDao();
            unidadedao.cadastrarUnidade(unidadebeans);
            JOptionPane.showMessageDialog(null, "Registro Salvo");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Gravar" + ex);
        }
    }

    private void ExcluirUnidade() {

        try {
            UnidadeDao unidadedao = new UnidadeDao();
            unidadedao.excluirUnidade(Integer.valueOf(jtfCodigo.getText()));
            JOptionPane.showMessageDialog(null, "Registro Excluido com Sucesso");
            BuscarUnidade();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Excluir" + ex);
        }
    }

    private void AlteraUnidade() {
        UnidadeBeans unidadebeans = new UnidadeBeans();
        unidadebeans.setId(Integer.valueOf(jtfCodigo.getText()));
        unidadebeans.setBairro(jtfBairro.getText());
        unidadebeans.setCep(jtfCEP.getText());
        unidadebeans.setCidade(jtfCidade.getText());
        unidadebeans.setComplemento(jtfComplemento.getText());
        unidadebeans.setEndereco(jtfEndereco.getText());
        unidadebeans.setFantasia(jtfFantasia.getText());
        unidadebeans.setTelefone(jtfFone.getText());
        unidadebeans.setNumero(jtfN.getText());
        unidadebeans.setRazao(JTrazaosocial.getText());
        unidadebeans.setCnpj(jFcnpj.getText());
        unidadebeans.setLogo("");

        try {
            UnidadeDao unidadedao = new UnidadeDao();
            unidadedao.alterarUnidade(unidadebeans);
            JOptionPane.showMessageDialog(null, "Registro Alterado");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Alterar Registro" + ex);
        }
    }

    private void TamanhoTabela() {
        jtUnidade.getColumnModel().getColumn(0).setMaxWidth(60);
        jtUnidade.getColumnModel().getColumn(0).setMinWidth(60);
        jtUnidade.getColumnModel().getColumn(1).setMaxWidth(250);
        jtUnidade.getColumnModel().getColumn(1).setMinWidth(250);
        jtUnidade.getColumnModel().getColumn(2).setMaxWidth(250);
        jtUnidade.getColumnModel().getColumn(2).setMinWidth(250);
        jtUnidade.getColumnModel().getColumn(3).setMaxWidth(250);
        jtUnidade.getColumnModel().getColumn(3).setMinWidth(250);
        jtUnidade.getColumnModel().getColumn(4).setMaxWidth(250);
        jtUnidade.getColumnModel().getColumn(4).setMinWidth(250);
        jtUnidade.getColumnModel().getColumn(5).setMaxWidth(250);
        jtUnidade.getColumnModel().getColumn(5).setMinWidth(250);

    }
}
